#coding: utf-8
 # ----------------------------------------------------------------------------
 # ****************************************************************************
 # * @file SharedMemory.py
 # * @author Isaac Jesus da Silva - ROBOFEI-HT - FEI 😛
 # * @version V0.0.2
 # * @created 08/09/2015
 # * @Modified 16/09/2015
 # * @e-mail isaac25silva@yahoo.com.br
 # * @brief Shared Memory
 # ****************************************************************************
 # ****************************************************************************
import ctypes
import time
import os


# Classe do BlackBoard--------------------------------------------------------------------
class SharedMemory(object):
# Classe que lê e escreve na memória compartilhada do sistema '''

    def shd_constructor(self,KEY):
        #print "Start the Class Blackboard"
        # Usando memoria compartilhada a partir das funções do c++-------------------------------------------------------
        try:
            self.testlib = ctypes.CDLL('../../build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
        except OSError:
            try:
                self.testlib = ctypes.CDLL('../build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
            except OSError:
                self.testlib = ctypes.CDLL('../AI/build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
        self.testlib.using_shared_memory.restype = ctypes.POINTER(ctypes.c_int)
        mem = self.testlib.using_shared_memory(KEY)         #using c++ function
        #print 'python', mem
        self.testlib.read_float.restype = ctypes.c_float #defining the return type, that case defining float
        self.testlib.read_int.restype = ctypes.c_int #defining the return type, that case defining int
        return mem
        #--------------------------------------------------------------------------------------------------------------------

    # Criando função que escreve float--------------------------------------------------------
    def write_float(self, mem, variable, value):
        self.testlib.write_float(mem, ctypes.c_int(self.variable_float[variable]), ctypes.c_float(value))
    #-----------------------------------------------------------------------------------------


    # Criando função que escreve float--------------------------------------------------------
    def write_floatDynamic(self, mem, variable,index, value):
        self.testlib.write_float(mem, ctypes.c_int(self.variable_float[variable]+index), ctypes.c_float(value))
    #-----------------------------------------------------------------------------------------

    # Criando função que escreve float--------------------------------------------------------
    def write_int(self, mem, variable, value):
        self.testlib.write_int(mem, ctypes.c_int(self.variable_int[variable]), ctypes.c_int(int(value)))
    #-----------------------------------------------------------------------------------------

    # Criando função que lê float--------------------------------------------------------
    def read_float(self, mem, variable):
        return self.testlib.read_float(mem, ctypes.c_int(self.variable_float[variable]))
    #-----------------------------------------------------------------------------------------

    # Criando função que lê float--------------------------------------------------------
    def read_int(self, mem, variable):
        return self.testlib.read_int(mem, ctypes.c_int(self.variable_int[variable]))
    #-----------------------------------------------------------------------------------------

    variable_int = {
        'PLANNING_COMMAND' : 0,
        'PLANNING_PARAMETER_VEL': 1,
        'PLANNING_PARAMETER_ANGLE': 2,
        'IMU_STATE' : 3,
        'IMU_RESET': 4,
        'CONTROL_ACTION': 13,
        'CONTROL_HEIGHT_A': 14,
        'CONTROL_HEIGHT_B': 15,
        'CONTROL_HEIGHT_C': 16,
        'DECISION_ACTION_A': 17,
        'DECISION_ACTION_B': 18,
        'DECISION_STATE': 19,
        'DECISION_POSITION_A': 20,
        'DECISION_POSITION_B': 21,
        'DECISION_POSITION_C': 22,
        'DECISION_BALL_POS': 23,
        'DECISION_OPP1_POS': 24,
        'DECISION_OPP2_POS': 25,
        'DECISION_OPP3_POS': 26,
        'COM_ACTION_ROBOT1': 27,
        'COM_ACTION_ROBOT2': 28,
        'COM_ACTION_ROBOT3': 29,
        'COM_STATE_ROBOT1': 30,
        'COM_STATE_ROBOT2': 31,
        'COM_STATE_ROBOT3': 32,
        'COM_POS_ROBOT1': 33,
        'COM_POS_ROBOT2': 34,
        'COM_POS_ROBOT3': 35,
        'COM_POS_BALL_ROBOT1': 36,
        'COM_POS_BALL_ROBOT2': 37,
        'COM_POS_BALL_ROBOT3': 38,
        'COM_POS_OPP_A_ROBOT1': 39,
        'COM_POS_OPP_A_ROBOT2': 40,
        'COM_POS_OPP_A_ROBOT3': 41,
        'COM_POS_OPP_A_ROBOT4': 42,
        'COM_POS_OPP_B_ROBOT1': 43,
        'COM_POS_OPP_B_ROBOT2': 44,
        'COM_POS_OPP_B_ROBOT3': 45,
        'COM_POS_OPP_B_ROBOT4': 46,
        'COM_POS_OPP_C_ROBOT1': 47,
        'COM_POS_OPP_C_ROBOT2': 48,
        'COM_POS_OPP_C_ROBOT3': 49,
        'COM_POS_OPP_C_ROBOT4': 50,
        'COM_REFEREE': 51,
        'LOCALIZATION_X': 52,
        'LOCALIZATION_Y': 53,
        'LOCALIZATION_THETA': 54,
        'VISION_LOST': 57,
        'DECISION_SEARCH_ON': 58,
        'DECISION_ACTION_VISION': 59,
        'VISION_MOTOR1_GOAL': 60,
        'VISION_MOTOR2_GOAL': 61,
        'VISION_SEARCH_GOAL': 62,
        'VISION_LOST_GOAL': 63,
        'VISION_STATE': 64,
        'ROBOT_NUMBER': 65,
        'VISION_pos_servo1': 66,
        'VISION_pos_servo2': 67,
        'COM_POS_ORIENT_QUALIT_ROBOT_A': 68,
        'COM_POS_DIST_QUALIT_ROBOT_A': 69,
        'COM_POS_ORIENT_QUALIT_ROBOT_B': 70,
        'COM_POS_DIST_QUALIT_ROBOT_B': 71,
        'COM_POS_ORIENT_QUALIT_ROBOT_C': 72,
        'COM_POS_DIST_QUALIT_ROBOT_C': 73,
        'VISION_DELTA_ORIENT': 74,
        'LOCALIZATION_FIND_ROBOT': 75,
        'RECEIVED_ROBOT_SENDING': 76,
        'RECEIVED_QUAL_ORIENT': 77,
        'RECEIVED_QUAL_DIST': 78,
        'RECEIVED_ROBOT_SEEN': 79,
        'CONTROL_MESSAGES': 80,
        'ASKED_QUALIT_DIRECT': 81,
        'ASKED_QUALIT_DISTANCE': 82,
        'ASKED_RELATED_ROBOT': 83,
        'CONTROL_MOVING': 84,
        'ROBOT_VIEW_ROTATE': 100,
        'CONTROL_WORKING': 101,
        'VISION_WORKING': 102,
        'LOCALIZATION_WORKING': 103,
        'DECISION_WORKING': 104,
        'IMU_WORKING': 105,
        'VOLTAGE': 106,
        'DECISION_LOCALIZATION': 107,
        'iVISION_FIELD': 108,
    }

    variable_float = {
        "IMU_GYRO_X": 0,
        "IMU_GYRO_Y": 1,
        "IMU_GYRO_Z": 2,
        "IMU_ACCEL_X": 3,
        "IMU_ACCEL_Y": 4,
        "IMU_ACCEL_Z": 5,
        "IMU_COMPASS_X": 6,
        "IMU_COMPASS_Y": 7,
        "IMU_COMPASS_Z": 8,
        "IMU_EULER_X": 9,
        "IMU_EULER_Y": 10,
        "IMU_EULER_Z": 11,
        "IMU_QUAT_X": 12,
        "IMU_QUAT_Y": 13,
        "IMU_QUAT_Z": 14,
        "VISION_AREA_SEGMENT": 15,
        "VISION_BALL_X": 16,
        "VISION_BALL_Y": 17,
        "VISION_BALL_TAG": 18,
        "VISION_BALL_TIME": 19,
        "VISION_BALL_MOV": 20,
        "VISION_LAND_X": 21,
        "VISION_LAND_Y": 22,
        "VISION_LAND_TAG": 23,
        "VISION_LAND_TIME": 24,
        "VISION_LAND_MOV": 25,
        "VISION_RB01_TAG": 26,
        "VISION_RB01_X": 27,
        "VISION_RB01_Y": 28,
        "VISION_RB01_TIME": 29,
        "VISION_RB01_MOV": 30,
        "VISION_RB02_TAG": 31,
        "VISION_RB02_X": 32,
        "VISION_RB02_Y": 33,
        "VISION_RB02_TIME": 34,
        "VISION_RB02_MOV": 35,
        "VISION_RB03_TAG": 36,
        "VISION_RB03_X": 37,
        "VISION_RB03_Y": 38,
        "VISION_RB03_TIME": 39,
        "VISION_RB03_MOV": 40,
        "VISION_RB04_TAG": 41,
        "VISION_RB04_X": 42,
        "VISION_RB04_Y": 43,
        "VISION_RB04_TIME": 44,
        "VISION_RB04_MOV": 45,
        "VISION_RB05_TAG": 46,
        "VISION_RB05_X": 47,
        "VISION_RB05_Y": 48,
        "VISION_RB05_TIME": 49,
        "VISION_RB05_MOV": 50,
        "VISION_RB06_TAG": 51,
        "VISION_RB06_X": 52,
        "VISION_RB06_Y": 53,
        "VISION_RB06_TIME": 54,
        "VISION_RB06_MOV": 55,
        "VISION_RB07_TAG": 56,
        "VISION_RB07_X": 57,
        "VISION_RB07_Y": 58,
        "VISION_RB07_TIME": 59,
        "VISION_RB07_MOV": 60,
        "VISION_RB08_TAG": 61,
        "VISION_RB08_X": 62,
        "VISION_RB08_Y": 63,
        "VISION_RB08_TIME": 64,
        "VISION_RB08_MOV": 65,
        "VISION_RB09_TAG": 66,
        "VISION_RB09_X": 67,
        "VISION_RB09_Y": 68,
        "VISION_RB09_TIME": 69,
        "VISION_RB09_MOV": 70,
        "VISION_RB10_TAG": 71,
        "VISION_RB10_X": 72,
        "VISION_RB10_Y": 73,
        "VISION_RB10_TIME": 74,
        "VISION_RB10_MOV": 75,
        "VISION_RB11_TAG": 76,
        "VISION_RB11_X": 77,
        "VISION_RB11_Y": 78,
        "VISION_RB11_TIME": 79,
        "VISION_RB11_MOV": 80,
        "VISION_RB12_TAG": 81,
        "VISION_RB12_X": 82,
        "VISION_RB12_Y": 83,
        "VISION_RB12_TIME": 84,
        "VISION_RB12_MOV": 85,
        "VISION_RB13_TAG": 86,
        "VISION_RB13_X": 87,
        "VISION_RB13_Y": 88,
        "VISION_RB13_TIME": 89,
        "VISION_RB13_MOV": 90,
        "VISION_RB14_TAG": 91,
        "VISION_RB14_X": 92,
        "VISION_RB14_Y": 93,
        "VISION_RB14_TIME": 94,
        "VISION_RB14_MOV": 95,
        "VISION_RB15_TAG": 96,
        "VISION_RB15_X": 97,
        "VISION_RB15_Y": 98,
        "VISION_RB15_TIME": 99,
        "VISION_RB15_MOV": 100,
        "VISION_RB16_TAG": 101,
        "VISION_RB16_X": 102,
        "VISION_RB16_Y": 103,
        "VISION_RB16_TIME": 104,
        "VISION_RB16_MOV": 105,
        "VISION_RB17_TAG": 106,
        "VISION_RB17_X": 107,
        "VISION_RB17_Y": 108,
        "VISION_RB17_TIME": 109,
        "VISION_RB17_MOV": 110,
        "VISION_RB18_TAG": 111,
        "VISION_RB18_X": 112,
        "VISION_RB18_Y": 113,
        "VISION_RB18_TIME": 114,
        "VISION_RB18_MOV": 115,
        "VISION_RB19_TAG": 116,
        "VISION_RB19_X": 117,
        "VISION_RB19_Y": 118,
        "VISION_RB19_TIME": 119,
        "VISION_RB19_MOV": 120,
        "VISION_RB20_TAG": 121,
        "VISION_RB20_X": 122,
        "VISION_RB20_Y": 123,
        "VISION_RB20_TIME": 124,
        "VISION_RB20_MOV": 125,
        "VISION_RB21_TAG": 126,
        "VISION_RB21_X": 127,
        "VISION_RB21_Y": 128,
        "VISION_RB21_TIME": 129,
        "VISION_RB21_MOV": 130,
        "VISUAL_MEMORY_LAND_LOC": 131,
        "VISUAL_MEMORY_LAND_X": 132,
        "VISUAL_MEMORY_LAND_Y": 133,
        "VISUAL_MEMORY_BALL_LOC": 134,
        "VISUAL_MEMORY_BALL_X": 135,
        "VISUAL_MEMORY_BALL_Y": 136,
        "VISUAL_MEMORY_AL_01_LOC": 137,
        "VISUAL_MEMORY_AL_01_X": 138,
        "VISUAL_MEMORY_AL_01_Y": 139,
        "VISUAL_MEMORY_AL_01_MAX_VEL": 140,
        "VISUAL_MEMORY_AL_02_LOC": 141,
        "VISUAL_MEMORY_AL_02_X": 142,
        "VISUAL_MEMORY_AL_02_Y": 143,
        "VISUAL_MEMORY_AL_02_MAX_VEL": 144,
        "VISUAL_MEMORY_AL_03_LOC": 145,
        "VISUAL_MEMORY_AL_03_X": 146,
        "VISUAL_MEMORY_AL_03_Y": 147,
        "VISUAL_MEMORY_AL_03_MAX_VEL": 148,
        "VISUAL_MEMORY_AL_04_LOC": 149,
        "VISUAL_MEMORY_AL_04_X": 150,
        "VISUAL_MEMORY_AL_04_Y": 151,
        "VISUAL_MEMORY_AL_04_MAX_VEL": 152,
        "VISUAL_MEMORY_AL_05_LOC": 153,
        "VISUAL_MEMORY_AL_05_X": 154,
        "VISUAL_MEMORY_AL_05_Y": 155,
        "VISUAL_MEMORY_AL_05_MAX_VEL": 156,
        "VISUAL_MEMORY_AL_06_LOC": 157,
        "VISUAL_MEMORY_AL_06_X": 158,
        "VISUAL_MEMORY_AL_06_Y": 159,
        "VISUAL_MEMORY_AL_06_MAX_VEL": 160,
        "VISUAL_MEMORY_AL_07_LOC": 161,
        "VISUAL_MEMORY_AL_07_X": 162,
        "VISUAL_MEMORY_AL_07_Y": 163,
        "VISUAL_MEMORY_AL_07_MAX_VEL": 164,
        "VISUAL_MEMORY_AL_08_LOC": 165,
        "VISUAL_MEMORY_AL_08_X": 166,
        "VISUAL_MEMORY_AL_08_Y": 167,
        "VISUAL_MEMORY_AL_08_MAX_VEL": 168,
        "VISUAL_MEMORY_AL_09_LOC": 169,
        "VISUAL_MEMORY_AL_09_X": 170,
        "VISUAL_MEMORY_AL_09_Y": 171,
        "VISUAL_MEMORY_AL_09_MAX_VEL": 172,
        "VISUAL_MEMORY_AL_10_LOC": 173,
        "VISUAL_MEMORY_AL_10_X": 174,
        "VISUAL_MEMORY_AL_10_Y": 175,
        "VISUAL_MEMORY_AL_10_MAX_VEL": 176,
        "VISUAL_MEMORY_OP_01_LOC": 177,
        "VISUAL_MEMORY_OP_01_X": 178,
        "VISUAL_MEMORY_OP_01_Y": 179,
        "VISUAL_MEMORY_OP_01_MAX_VEL": 180,
        "VISUAL_MEMORY_OP_02_LOC": 181,
        "VISUAL_MEMORY_OP_02_X": 182,
        "VISUAL_MEMORY_OP_02_Y": 183,
        "VISUAL_MEMORY_OP_02_MAX_VEL": 184,
        "VISUAL_MEMORY_OP_03_LOC": 185,
        "VISUAL_MEMORY_OP_03_X": 186,
        "VISUAL_MEMORY_OP_03_Y": 187,
        "VISUAL_MEMORY_OP_03_MAX_VEL": 188,
        "VISUAL_MEMORY_OP_04_LOC": 189,
        "VISUAL_MEMORY_OP_04_X": 190,
        "VISUAL_MEMORY_OP_04_Y": 191,
        "VISUAL_MEMORY_OP_04_MAX_VEL": 192,
        "VISUAL_MEMORY_OP_05_LOC": 193,
        "VISUAL_MEMORY_OP_05_X": 194,
        "VISUAL_MEMORY_OP_05_Y": 195,
        "VISUAL_MEMORY_OP_05_MAX_VEL": 196,
        "VISUAL_MEMORY_OP_06_LOC": 197,
        "VISUAL_MEMORY_OP_06_X": 198,
        "VISUAL_MEMORY_OP_06_Y": 199,
        "VISUAL_MEMORY_OP_06_MAX_VEL": 200,
        "VISUAL_MEMORY_OP_07_LOC": 201,
        "VISUAL_MEMORY_OP_07_X": 202,
        "VISUAL_MEMORY_OP_07_Y": 203,
        "VISUAL_MEMORY_OP_07_MAX_VEL": 204,
        "VISUAL_MEMORY_OP_08_LOC": 205,
        "VISUAL_MEMORY_OP_08_X": 206,
        "VISUAL_MEMORY_OP_08_Y": 207,
        "VISUAL_MEMORY_OP_08_MAX_VEL": 208,
        "VISUAL_MEMORY_OP_09_LOC": 209,
        "VISUAL_MEMORY_OP_09_X": 210,
        "VISUAL_MEMORY_OP_09_Y": 211,
        "VISUAL_MEMORY_OP_09_MAX_VEL": 212,
        "VISUAL_MEMORY_OP_10_LOC": 213,
        "VISUAL_MEMORY_OP_10_X": 214,
        "VISUAL_MEMORY_OP_10_Y": 215,
        "VISUAL_MEMORY_OP_10_MAX_VEL": 216,
        "VISUAL_MEMORY_OP_11_LOC": 217,
        "VISUAL_MEMORY_OP_11_X": 218,
        "VISUAL_MEMORY_OP_11_Y": 219,
        "VISUAL_MEMORY_OP_11_MAX_VEL": 220,
        "VISION_TILT_DEG": 221,
        "VISION_PAN_DEG": 222,
        "CBR_COORDINATOR": 223,
        "CBR_RUN": 224,
        "LOCALIZATION_BALL_X": 225,
        "LOCALIZATION_BALL_Y": 226,
        "LOCALIZATION_RBT01_X": 227,
        "LOCALIZATION_RBT01_Y": 228,
        "LOCALIZATION_RBT02_X": 229,
        "LOCALIZATION_RBT02_Y": 230,
        "LOCALIZATION_RBT03_X": 231,
        "LOCALIZATION_RBT03_Y": 232,
        "LOCALIZATION_RBT04_X": 233,
        "LOCALIZATION_RBT04_Y": 234,
        "LOCALIZATION_RBT05_X": 235,
        "LOCALIZATION_RBT05_Y": 236,
        "LOCALIZATION_RBT06_X": 237,
        "LOCALIZATION_RBT06_Y": 238,
        "LOCALIZATION_RBT07_X": 239,
        "LOCALIZATION_RBT07_Y": 240,
        "LOCALIZATION_RBT08_X": 241,
        "LOCALIZATION_RBT08_Y": 242,
        "LOCALIZATION_RBT09_X": 243,
        "LOCALIZATION_RBT09_Y": 244,
        "LOCALIZATION_RBT10_X": 245,
        "LOCALIZATION_RBT10_Y": 246,
        "LOCALIZATION_RBT11_X": 247,
        "LOCALIZATION_RBT11_Y": 248,
        "LOCALIZATION_OPP01_X": 249,
        "LOCALIZATION_OPP01_Y": 250,
        "LOCALIZATION_OPP02_X": 251,
        "LOCALIZATION_OPP02_Y": 252,
        "LOCALIZATION_OPP03_X": 253,
        "LOCALIZATION_OPP03_Y": 254,
        "LOCALIZATION_OPP04_X": 255,
        "LOCALIZATION_OPP04_Y": 256,
        "LOCALIZATION_OPP05_X": 257,
        "LOCALIZATION_OPP05_Y": 258,
        "LOCALIZATION_OPP06_X": 259,
        "LOCALIZATION_OPP06_Y": 260,
        "LOCALIZATION_OPP07_X": 261,
        "LOCALIZATION_OPP07_Y": 262,
        "LOCALIZATION_OPP08_X": 263,
        "LOCALIZATION_OPP08_Y": 264,
        "LOCALIZATION_OPP09_X": 265,
        "LOCALIZATION_OPP09_Y": 266,
        "LOCALIZATION_OPP10_X": 267,
        "LOCALIZATION_OPP10_Y": 268,
        "LOCALIZATION_OPP11_X": 269,
        "LOCALIZATION_OPP11_Y": 270,
        "DECISION_RBT01_DIST_BALL": 271,
        "DECISION_RBT02_DIST_BALL": 272,
        "DECISION_RBT03_DIST_BALL": 273,
        "DECISION_RBT04_DIST_BALL": 274,
        "VISION_FIRST_GOALPOST": 275,
        "VISION_SECOND_GOALPOST": 276,
        "VISION_THIRD_GOALPOST": 277,
        "VISION_FOURTH_GOALPOST": 278,
        "fVISION_FIELD": 279
    }
#------------------------------------------------------------------------------------------
