#coding: utf-8
 # ----------------------------------------------------------------------------
 # ****************************************************************************
 # * @file SharedMemory.py
 # * @author Isaac Jesus da Silva - ROBOFEI-HT - FEI 😛
 # * @version V0.0.2
 # * @created 08/09/2015
 # * @Modified 16/09/2015
 # * @e-mail isaac25silva@yahoo.com.br
 # * @brief Shared Memory
 # ****************************************************************************
 # ****************************************************************************
import ctypes
import time
import os


# Classe do BlackBoard--------------------------------------------------------------------
class SharedMemory(object):
# Classe que lê e escreve na memória compartilhada do sistema '''

    def shd_constructor(self,KEY):
        #print "Start the Class Blackboard"
        # Usando memoria compartilhada a partir das funções do c++-------------------------------------------------------
        try:
            self.testlib = ctypes.CDLL('../../build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
        except OSError:
            try:
                self.testlib = ctypes.CDLL('../build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
            except OSError:
                self.testlib = ctypes.CDLL('../AI/build/lib/libblackboardpy.so') #chama a library que contem as funções em c++
        self.testlib.using_shared_memory.restype = ctypes.POINTER(ctypes.c_int)
        mem = self.testlib.using_shared_memory(KEY)         #using c++ function
        #print 'python', mem
        self.testlib.read_float.restype = ctypes.c_float #defining the return type, that case defining float
        self.testlib.read_int.restype = ctypes.c_int #defining the return type, that case defining int
        self.testlib.read_double.restype = ctypes.c_double #defining the return type, that case defining double
        return mem
        #--------------------------------------------------------------------------------------------------------------------

    # Criando função que escreve float--------------------------------------------------------
    def write_float(self, mem, variable, value):
        self.testlib.write_float(mem, ctypes.c_int(self.variable_float[variable]), ctypes.c_float(value))
    #-----------------------------------------------------------------------------------------

    # Criando função que escreve double--------------------------------------------------------
    def write_double(self, mem, variable, value):
        self.testlib.write_double(mem, ctypes.c_int(self.variable_double[variable]), ctypes.c_double(value))
    #-----------------------------------------------------------------------------------------

    # Criando função que escreve float--------------------------------------------------------
    def write_floatDynamic(self, mem, variable,index, value):
        self.testlib.write_float(mem, ctypes.c_int(self.variable_float[variable]+index), ctypes.c_float(value))
    #-----------------------------------------------------------------------------------------

    # Criando função que escreve float--------------------------------------------------------
    def write_int(self, mem, variable, value):
        self.testlib.write_int(mem, ctypes.c_int(self.variable_int[variable]), ctypes.c_int(int(value)))
    #-----------------------------------------------------------------------------------------

    # Criando função que lê float--------------------------------------------------------
    def read_float(self, mem, variable):
        return self.testlib.read_float(mem, ctypes.c_int(self.variable_float[variable]))
    #-----------------------------------------------------------------------------------------

    # Criando função que lê double--------------------------------------------------------
    def read_double(self, mem, variable):
        return self.testlib.read_double(mem, ctypes.c_int(self.variable_double[variable]))
    #-----------------------------------------------------------------------------------------

    # Criando função que lê float--------------------------------------------------------
    def read_int(self, mem, variable):
        return self.testlib.read_int(mem, ctypes.c_int(self.variable_int[variable]))
    #-----------------------------------------------------------------------------------------

    variable_int = {
        "PLANNING_COMMAND": 0,
        "PLANNING_PARAMETER_VEL": 1,
        "PLANNING_PARAMETER_ANGLE": 2,
        "IMU_STATE": 3,
        "IMU_RESET": 4,
        "CONTROL_ACTION": 5,
        "CONTROL_HEIGHT_A": 6,
        "CONTROL_HEIGHT_B": 7,
        "CONTROL_HEIGHT_C": 8,
        "DECISION_ACTION_A": 9,
        "DECISION_ACTION_B": 10,
        "DECISION_STATE": 11,
        "DECISION_POSITION_A": 12,
        "DECISION_POSITION_B": 13,
        "DECISION_POSITION_C": 14,
        "DECISION_BALL_POS": 15,
        "DECISION_OPP1_POS": 16,
        "DECISION_OPP2_POS": 17,
        "DECISION_OPP3_POS": 18,
        "COM_ACTION_ROBOT1": 19,
        "COM_ACTION_ROBOT2": 20,
        "COM_ACTION_ROBOT3": 21,
        "COM_STATE_ROBOT1": 22,
        "COM_STATE_ROBOT2": 23,
        "COM_STATE_ROBOT3": 24,
        "COM_POS_ROBOT1": 25,
        "COM_POS_ROBOT2": 26,
        "COM_POS_ROBOT3": 27,
        "COM_POS_BALL_ROBOT1": 28,
        "COM_POS_BALL_ROBOT2": 29,
        "COM_POS_BALL_ROBOT3": 30,
        "COM_POS_OPP_A_ROBOT1": 31,
        "COM_POS_OPP_A_ROBOT2": 32,
        "COM_POS_OPP_A_ROBOT3": 33,
        "COM_POS_OPP_A_ROBOT4": 34,
        "COM_POS_OPP_B_ROBOT1": 35,
        "COM_POS_OPP_B_ROBOT2": 36,
        "COM_POS_OPP_B_ROBOT3": 37,
        "COM_POS_OPP_B_ROBOT4": 38,
        "COM_POS_OPP_C_ROBOT1": 39,
        "COM_POS_OPP_C_ROBOT2": 40,
        "COM_POS_OPP_C_ROBOT3": 41,
        "COM_POS_OPP_C_ROBOT4": 42,
        "COM_REFEREE": 43,
        "LOCALIZATION_X": 44,
        "LOCALIZATION_Y": 45,
        "LOCALIZATION_THETA": 46,
        "VISION_LOST": 47,
        "DECISION_SEARCH_ON": 48,
        "DECISION_ACTION_VISION": 49,
        "VISION_MOTOR1_GOAL": 50,
        "VISION_MOTOR2_GOAL": 51,
        "VISION_SEARCH_GOAL": 52,
        "VISION_LOST_GOAL": 53,
        "VISION_STATE": 54,
        "ROBOT_NUMBER": 55,
        "VISION_pos_servo1": 56,
        "VISION_pos_servo2": 57,
        "VISION_BALL_TAG": 58,
        "VISION_BALL_MOV": 59,
        "VISION_LAND_TAG": 60,
        "VISION_LAND_MOV": 61,
        "VISION_RB01_TAG": 62,
        "VISION_RB01_MOV": 63,
        "VISION_RB02_TAG": 64,
        "VISION_RB02_MOV": 65,
        "VISION_RB03_TAG": 66,
        "VISION_RB03_MOV": 67,
        "VISION_RB04_TAG": 68,
        "VISION_RB04_MOV": 69,
        "VISION_RB05_TAG": 70,
        "VISION_RB05_MOV": 71,
        "VISION_RB06_TAG": 72,
        "VISION_RB06_MOV": 73,
        "VISION_RB07_TAG": 74,
        "VISION_RB07_MOV": 75,
        "VISION_RB08_TAG": 76,
        "VISION_RB08_MOV": 77,
        "VISION_RB09_TAG": 78,
        "VISION_RB09_MOV": 79,
        "VISION_RB10_TAG": 80,
        "VISION_RB10_MOV": 81,
        "VISION_RB11_TAG": 82,
        "VISION_RB11_MOV": 83,
        "VISION_RB12_TAG": 84,
        "VISION_RB12_MOV": 85,
        "VISION_RB13_TAG": 86,
        "VISION_RB13_MOV": 87,
        "VISION_RB14_TAG": 88,
        "VISION_RB14_MOV": 89,
        "VISION_RB15_TAG": 90,
        "VISION_RB15_MOV": 91,
        "VISION_RB16_TAG": 92,
        "VISION_RB16_MOV": 93,
        "VISION_RB17_TAG": 94,
        "VISION_RB17_MOV": 95,
        "VISION_RB18_TAG": 96,
        "VISION_RB18_MOV": 97,
        "VISION_RB19_TAG": 98,
        "VISION_RB19_MOV": 99,
        "VISION_RB20_TAG": 100,
        "VISION_RB20_MOV": 101,
        "VISION_RB21_TAG": 102,
        "VISION_RB21_MOV": 103,
        "COM_POS_ORIENT_QUALIT_ROBOT_A": 104,
        "COM_POS_DIST_QUALIT_ROBOT_A": 105,
        "COM_POS_ORIENT_QUALIT_ROBOT_B": 106,
        "COM_POS_DIST_QUALIT_ROBOT_B": 107,
        "COM_POS_ORIENT_QUALIT_ROBOT_C": 108,
        "COM_POS_DIST_QUALIT_ROBOT_C": 109,
        "VISION_DELTA_ORIENT": 110,
        "LOCALIZATION_FIND_ROBOT": 111,
        "RECEIVED_ROBOT_SENDING": 112,
        "RECEIVED_QUAL_ORIENT": 113,
        "RECEIVED_QUAL_DIST": 114,
        "RECEIVED_ROBOT_SEEN": 115,
        "CONTROL_MESSAGES": 116,
        "ASKED_QUALIT_DIRECT": 117,
        "ASKED_QUALIT_DISTANCE": 118,
        "ASKED_RELATED_ROBOT": 119,
        "CONTROL_MOVING": 120,
        "ROBOT_VIEW_ROTATE": 121,
        "CONTROL_WORKING": 122,
        "VISION_WORKING": 123,
        "LOCALIZATION_WORKING": 124,
        "DECISION_WORKING": 125,
        "IMU_WORKING": 126,
        "VOLTAGE": 127,
        "DECISION_LOCALIZATION": 128,
        "iVISION_FIELD": 129
    }

    variable_float = {
        "IMU_GYRO_X": 0,
        "IMU_GYRO_Y": 1,
        "IMU_GYRO_Z": 2,
        "IMU_ACCEL_X": 3,
        "IMU_ACCEL_Y": 4,
        "IMU_ACCEL_Z": 5,
        "IMU_COMPASS_X": 6,
        "IMU_COMPASS_Y": 7,
        "IMU_COMPASS_Z": 8,
        "IMU_EULER_X": 9,
        "IMU_EULER_Y": 10,
        "IMU_EULER_Z": 11,
        "IMU_QUAT_X": 12,
        "IMU_QUAT_Y": 13,
        "IMU_QUAT_Z": 14,
        "VISION_AREA_SEGMENT": 15,
        "VISION_BALL_X": 16,
        "VISION_BALL_Y": 17,
        "VISION_LAND_X": 18,
        "VISION_LAND_Y": 19,
        "VISION_RB01_X": 20,
        "VISION_RB01_Y": 21,
        "VISION_RB02_X": 22,
        "VISION_RB02_Y": 23,
        "VISION_RB03_X": 24,
        "VISION_RB03_Y": 25,
        "VISION_RB04_X": 26,
        "VISION_RB04_Y": 27,
        "VISION_RB05_X": 28,
        "VISION_RB05_Y": 29,
        "VISION_RB06_X": 30,
        "VISION_RB06_Y": 31,
        "VISION_RB07_X": 32,
        "VISION_RB07_Y": 33,
        "VISION_RB08_X": 34,
        "VISION_RB08_Y": 35,
        "VISION_RB09_X": 36,
        "VISION_RB09_Y": 37,
        "VISION_RB10_X": 38,
        "VISION_RB10_Y": 39,
        "VISION_RB11_X": 40,
        "VISION_RB11_Y": 41,
        "VISION_RB12_X": 42,
        "VISION_RB12_Y": 43,
        "VISION_RB13_X": 44,
        "VISION_RB13_Y": 45,
        "VISION_RB14_X": 46,
        "VISION_RB14_Y": 47,
        "VISION_RB15_X": 48,
        "VISION_RB15_Y": 49,
        "VISION_RB16_X": 50,
        "VISION_RB16_Y": 51,
        "VISION_RB17_X": 52,
        "VISION_RB17_Y": 53,
        "VISION_RB18_X": 54,
        "VISION_RB18_Y": 55,
        "VISION_RB19_X": 56,
        "VISION_RB19_Y": 57,
        "VISION_RB20_X": 58,
        "VISION_RB20_Y": 59,
        "VISION_RB21_X": 60,
        "VISION_RB21_Y": 61,
        "VISUAL_MEMORY_LAND_LOC": 62,
        "VISUAL_MEMORY_LAND_X": 63,
        "VISUAL_MEMORY_LAND_Y": 64,
        "VISUAL_MEMORY_BALL_LOC": 65,
        "VISUAL_MEMORY_BALL_X": 66,
        "VISUAL_MEMORY_BALL_Y": 67,
        "VISUAL_MEMORY_AL_01_LOC": 68,
        "VISUAL_MEMORY_AL_01_X": 69,
        "VISUAL_MEMORY_AL_01_Y": 70,
        "VISUAL_MEMORY_AL_01_MAX_VEL": 71,
        "VISUAL_MEMORY_AL_02_LOC": 72,
        "VISUAL_MEMORY_AL_02_X": 73,
        "VISUAL_MEMORY_AL_02_Y": 74,
        "VISUAL_MEMORY_AL_02_MAX_VEL": 75,
        "VISUAL_MEMORY_AL_03_LOC": 76,
        "VISUAL_MEMORY_AL_03_X": 77,
        "VISUAL_MEMORY_AL_03_Y": 78,
        "VISUAL_MEMORY_AL_03_MAX_VEL": 79,
        "VISUAL_MEMORY_AL_04_LOC": 80,
        "VISUAL_MEMORY_AL_04_X": 81,
        "VISUAL_MEMORY_AL_04_Y": 82,
        "VISUAL_MEMORY_AL_04_MAX_VEL": 83,
        "VISUAL_MEMORY_AL_05_LOC": 84,
        "VISUAL_MEMORY_AL_05_X": 85,
        "VISUAL_MEMORY_AL_05_Y": 86,
        "VISUAL_MEMORY_AL_05_MAX_VEL": 87,
        "VISUAL_MEMORY_AL_06_LOC": 88,
        "VISUAL_MEMORY_AL_06_X": 89,
        "VISUAL_MEMORY_AL_06_Y": 90,
        "VISUAL_MEMORY_AL_06_MAX_VEL": 91,
        "VISUAL_MEMORY_AL_07_LOC": 92,
        "VISUAL_MEMORY_AL_07_X": 93,
        "VISUAL_MEMORY_AL_07_Y": 94,
        "VISUAL_MEMORY_AL_07_MAX_VEL": 95,
        "VISUAL_MEMORY_AL_08_LOC": 96,
        "VISUAL_MEMORY_AL_08_X": 97,
        "VISUAL_MEMORY_AL_08_Y": 98,
        "VISUAL_MEMORY_AL_08_MAX_VEL": 99,
        "VISUAL_MEMORY_AL_09_LOC": 100,
        "VISUAL_MEMORY_AL_09_X": 101,
        "VISUAL_MEMORY_AL_09_Y": 102,
        "VISUAL_MEMORY_AL_09_MAX_VEL": 103,
        "VISUAL_MEMORY_AL_10_LOC": 104,
        "VISUAL_MEMORY_AL_10_X": 105,
        "VISUAL_MEMORY_AL_10_Y": 106,
        "VISUAL_MEMORY_AL_10_MAX_VEL": 107,
        "VISUAL_MEMORY_OP_01_LOC": 108,
        "VISUAL_MEMORY_OP_01_X": 109,
        "VISUAL_MEMORY_OP_01_Y": 110,
        "VISUAL_MEMORY_OP_01_MAX_VEL": 111,
        "VISUAL_MEMORY_OP_02_LOC": 112,
        "VISUAL_MEMORY_OP_02_X": 113,
        "VISUAL_MEMORY_OP_02_Y": 114,
        "VISUAL_MEMORY_OP_02_MAX_VEL": 115,
        "VISUAL_MEMORY_OP_03_LOC": 116,
        "VISUAL_MEMORY_OP_03_X": 117,
        "VISUAL_MEMORY_OP_03_Y": 118,
        "VISUAL_MEMORY_OP_03_MAX_VEL": 119,
        "VISUAL_MEMORY_OP_04_LOC": 120,
        "VISUAL_MEMORY_OP_04_X": 121,
        "VISUAL_MEMORY_OP_04_Y": 122,
        "VISUAL_MEMORY_OP_04_MAX_VEL": 123,
        "VISUAL_MEMORY_OP_05_LOC": 124,
        "VISUAL_MEMORY_OP_05_X": 125,
        "VISUAL_MEMORY_OP_05_Y": 126,
        "VISUAL_MEMORY_OP_05_MAX_VEL": 127,
        "VISUAL_MEMORY_OP_06_LOC": 128,
        "VISUAL_MEMORY_OP_06_X": 129,
        "VISUAL_MEMORY_OP_06_Y": 130,
        "VISUAL_MEMORY_OP_06_MAX_VEL": 131,
        "VISUAL_MEMORY_OP_07_LOC": 132,
        "VISUAL_MEMORY_OP_07_X": 133,
        "VISUAL_MEMORY_OP_07_Y": 134,
        "VISUAL_MEMORY_OP_07_MAX_VEL": 135,
        "VISUAL_MEMORY_OP_08_LOC": 136,
        "VISUAL_MEMORY_OP_08_X": 137,
        "VISUAL_MEMORY_OP_08_Y": 138,
        "VISUAL_MEMORY_OP_08_MAX_VEL": 139,
        "VISUAL_MEMORY_OP_09_LOC": 140,
        "VISUAL_MEMORY_OP_09_X": 141,
        "VISUAL_MEMORY_OP_09_Y": 142,
        "VISUAL_MEMORY_OP_09_MAX_VEL": 143,
        "VISUAL_MEMORY_OP_10_LOC": 144,
        "VISUAL_MEMORY_OP_10_X": 145,
        "VISUAL_MEMORY_OP_10_Y": 146,
        "VISUAL_MEMORY_OP_10_MAX_VEL": 147,
        "VISUAL_MEMORY_OP_11_LOC": 148,
        "VISUAL_MEMORY_OP_11_X": 149,
        "VISUAL_MEMORY_OP_11_Y": 150,
        "VISUAL_MEMORY_OP_11_MAX_VEL": 151,
        "VISION_TILT_DEG": 152,
        "VISION_PAN_DEG": 153,
        "CBR_COORDINATOR": 154,
        "CBR_RUN": 155,
        "LOCALIZATION_BALL_X": 156,
        "LOCALIZATION_BALL_Y": 157,
        "LOCALIZATION_RBT01_X": 158,
        "LOCALIZATION_RBT01_Y": 159,
        "LOCALIZATION_RBT02_X": 160,
        "LOCALIZATION_RBT02_Y": 161,
        "LOCALIZATION_RBT03_X": 162,
        "LOCALIZATION_RBT03_Y": 163,
        "LOCALIZATION_RBT04_X": 164,
        "LOCALIZATION_RBT04_Y": 165,
        "LOCALIZATION_RBT05_X": 166,
        "LOCALIZATION_RBT05_Y": 167,
        "LOCALIZATION_RBT06_X": 168,
        "LOCALIZATION_RBT06_Y": 169,
        "LOCALIZATION_RBT07_X": 170,
        "LOCALIZATION_RBT07_Y": 171,
        "LOCALIZATION_RBT08_X": 172,
        "LOCALIZATION_RBT08_Y": 173,
        "LOCALIZATION_RBT09_X": 174,
        "LOCALIZATION_RBT09_Y": 175,
        "LOCALIZATION_RBT10_X": 176,
        "LOCALIZATION_RBT10_Y": 177,
        "LOCALIZATION_RBT11_X": 178,
        "LOCALIZATION_RBT11_Y": 179,
        "LOCALIZATION_OPP01_X": 180,
        "LOCALIZATION_OPP01_Y": 181,
        "LOCALIZATION_OPP02_X": 182,
        "LOCALIZATION_OPP02_Y": 183,
        "LOCALIZATION_OPP03_X": 184,
        "LOCALIZATION_OPP03_Y": 185,
        "LOCALIZATION_OPP04_X": 186,
        "LOCALIZATION_OPP04_Y": 187,
        "LOCALIZATION_OPP05_X": 188,
        "LOCALIZATION_OPP05_Y": 189,
        "LOCALIZATION_OPP06_X": 190,
        "LOCALIZATION_OPP06_Y": 191,
        "LOCALIZATION_OPP07_X": 192,
        "LOCALIZATION_OPP07_Y": 193,
        "LOCALIZATION_OPP08_X": 194,
        "LOCALIZATION_OPP08_Y": 195,
        "LOCALIZATION_OPP09_X": 196,
        "LOCALIZATION_OPP09_Y": 197,
        "LOCALIZATION_OPP10_X": 198,
        "LOCALIZATION_OPP10_Y": 199,
        "LOCALIZATION_OPP11_X": 200,
        "LOCALIZATION_OPP11_Y": 201,
        "DECISION_RBT01_DIST_BALL": 202,
        "DECISION_RBT02_DIST_BALL": 203,
        "DECISION_RBT03_DIST_BALL": 204,
        "DECISION_RBT04_DIST_BALL": 205,
        "VISION_FIRST_GOALPOST": 206,
        "VISION_SECOND_GOALPOST": 207,
        "VISION_THIRD_GOALPOST": 208,
        "VISION_FOURTH_GOALPOST": 209,
        "fVISION_FIELD": 210
    }

    variable_double = {
        "VISION_BALL_TIME": 0,
        "VISION_LAND_TIME": 1,
        "VISION_RB01_TIME": 2,
        "VISION_RB02_TIME": 3,
        "VISION_RB03_TIME": 4,
        "VISION_RB04_TIME": 5,
        "VISION_RB05_TIME": 6,
        "VISION_RB06_TIME": 7,
        "VISION_RB07_TIME": 8,
        "VISION_RB08_TIME": 9,
        "VISION_RB09_TIME": 10,
        "VISION_RB10_TIME": 11,
        "VISION_RB11_TIME": 12,
        "VISION_RB12_TIME": 13,
        "VISION_RB13_TIME": 14,
        "VISION_RB14_TIME": 15,
        "VISION_RB15_TIME": 16,
        "VISION_RB16_TIME": 17,
        "VISION_RB17_TIME": 18,
        "VISION_RB18_TIME": 19,
        "VISION_RB19_TIME": 20,
        "VISION_RB20_TIME": 21,
        "VISION_RB21_TIME": 22
    }
#------------------------------------------------------------------------------------------
